@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
SET "KEY="
IF /I "%1."=="/T." START "CHOICE_AUTO_SKIP" /MIN CMD /C TIMEOUT /T %2^&TASKKILL /IM xcopy.exe /F
FOR /F "DELIMS=" %%A IN ('XCOPY /W "!COMSPEC!" "!COMSPEC!" 2^>NUL ^|^| ECHO.TIMEOUT') DO ( IF NOT DEFINED KEY SET "KEY=%%A^!" )
IF !KEY:~-1!==^^ (SET "KEY=CARET") ELSE IF "!KEY:~-2!"=="&^!" (SET "KEY=AND") ELSE IF "!KEY:~-8,7!."=="TIMEOUT." (SET KEY=TIMEOUT) ELSE (SET "KEY=!KEY:~-2,1!")
IF /I "%1."=="/T." TASKKILL /FI "WINDOWTITLE eq CHOICE_AUTO_SKIP*" /IM cmd.exe 1>NUL
IF NOT DEFINED KEY SET KEY=BLANK
IF "!KEY!"==" " SET KEY=SPACE
IF "!KEY!"=="	" SET KEY=TAB
IF "!KEY!"=="," SET KEY=COMMA
IF "!KEY!"=="=" SET KEY=EQUAL
ENDLOCAL&SET CHOICE.INPUT=%KEY%
EXIT /B